'use strict';
const $=id=>document.getElementById(id),{tools,execute,rows}=Action20;
const params=new URLSearchParams(location.search),test=params.get('test')==='1'||['localhost','127.0.0.1',''].includes(location.hostname);
const BASE='https://allen3429.github.io/Allentrial20260812.github.io/public-good/action20/';
const API='https://abacus.jasoncameron.dev',NS='pglab-action20-20260914-v1';
let current=null,output='',isReal=false,category='全部',quiz=[],qi=0,score=0,missed=[],queue=Promise.resolve();
const store={get:k=>{try{return localStorage.getItem('a20:'+k)}catch{return null}},set:(k,v)=>{localStorage.setItem('a20:'+k,v)}};
const el=(tag,txt,cls)=>{const e=document.createElement(tag);if(txt!==undefined)e.textContent=txt;if(cls)e.className=cls;return e};
const source=(()=>{const s=params.get('utm_source')||'direct';return ['direct','github','npost','g0v','campus-volunteers','community','share'].includes(s)?s:'other'})();
function message(s){$('notice').textContent=s}
async function request(action,key){const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000);try{const r=await fetch(`${API}/${action}/${NS}/${key}`,{signal:c.signal,cache:'no-store',referrerPolicy:'no-referrer'});if(action==='get'&&r.status===404)return 0;if(!r.ok)throw Error('計數服務未成功回應。');const j=await r.json();if(!Number.isFinite(j.value))throw Error('計數資料格式不符。');return j.value}finally{clearTimeout(timer)}}
async function once(key){if(store.get(key))return;store.set('storage-check','1');await request('hit',key);store.set(key,'1')}
function metric(keys){if(test||!$('consent').checked)return Promise.resolve(false);queue=queue.then(async()=>{try{for(const k of keys)await once(k);$('metricstatus').textContent='事件已送達公開計數器；數字不是經查證人數。';return true}catch(e){$('metricstatus').textContent='計數未完整送達，未宣稱成功；工具仍可使用。可能是儲存被停用、網路或第三方服務故障。';return false}});return queue}
function complete(){if(isReal)metric(['visitors','completers','completed-'+current.id,'source-'+source+'-completed']);$('feedback').hidden=false}
function renderCards(){const query=$('search').value.trim().toLowerCase();const list=tools.filter(t=>(category==='全部'||t.group===category)&&[t.title,t.desc,t.audience].join(' ').toLowerCase().includes(query));$('cards').replaceChildren();list.forEach(t=>{const a=el('a',undefined,'card');a.href='?tool='+t.id+'#workspace';a.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey)return;e.preventDefault();openTool(t.id,true)});const num=el('div',undefined,'num');num.append(el('span',String(tools.indexOf(t)+1).padStart(2,'0')),el('span',t.group+' ↗'));a.append(num,el('h3',t.title),el('p',t.desc),el('div',t.audience,'audience'));$('cards').append(a)});$('count').textContent=`顯示 ${list.length} / 20 個工具`}
for(const c of ['全部',...new Set(tools.map(t=>t.group))]){const b=el('button',c);b.className='secondary';b.setAttribute('aria-pressed',c===category);b.onclick=()=>{category=c;[...$('filters').children].forEach(x=>x.setAttribute('aria-pressed',x.textContent===c));renderCards()};$('filters').append(b)}
$('search').oninput=renderCards;renderCards();
function openTool(id,push=false){const t=tools.find(t=>t.id===id);if(!t)return;current=t;output='';isReal=false;quiz=[];$('workspace').hidden=false;$('toolmeta').textContent=`${String(tools.indexOf(t)+1).padStart(2,'0')} / ${t.group} / ${t.audience}`;$('tooltitle').textContent=t.title;$('tooldesc').textContent=t.desc;$('fields').replaceChildren();for(const f of t.fields){const l=el('label',f.label,'field');const input=el(f.type==='textarea'?'textarea':'input');input.id='f-'+f.id;input.name=f.id;input.required=true;if(f.type!=='textarea')input.type=f.type;if(f.type==='number')input.step='any';input.maxLength=16000;l.htmlFor=input.id;input.placeholder=f.example;$('fields').append(l);l.append(input)}$('realinput').checked=false;$('error').textContent='';$('result').textContent='填入你的資料，或按「填入範例」試用。';$('resultstatus').textContent='等待你的輸入';$('quizbox').hidden=true;$('feedback').hidden=true;['download','copy','print'].forEach(k=>$(k).disabled=true);message('分享只包含工具代號，不包含你的輸入。');if(push){const u=new URL(location.href);u.searchParams.set('tool',id);u.hash='workspace';history.pushState({},'',u);$('tooltitle').focus()}document.title=t.title+'｜行動20'}
window.addEventListener('popstate',()=>{const id=new URLSearchParams(location.search).get('tool');if(id)openTool(id);else $('workspace').hidden=true});
$('demo').onclick=()=>{current.fields.forEach(f=>$('f-'+f.id).value=f.example);$('realinput').checked=false;$('error').textContent='';message('已載入範例。範例、內部測試不應勾選真實資料。')};
$('form').onsubmit=e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(e.target));output=execute(current.id,v);isReal=$('realinput').checked&&!test;$('result').textContent=output;$('error').textContent='';$('resultstatus').textContent=isReal?'你的工作結果（請人工確認）':test?'測試模式 · 不計入採用':'演示結果 · 不計入採用';['download','copy','print'].forEach(k=>$(k).disabled=false);$('feedback').hidden=true;if(current.id==='quiz'){quiz=rows(v.cards,2);qi=score=0;missed=[];$('quizbox').hidden=false;showQuestion()}else{$('quizbox').hidden=true;complete()}message('結果已產生，尚未自動儲存或發布。')}catch(err){output='';$('error').textContent=err.message;$('result').textContent='資料未通過檢查，請修正後重新產出。';$('feedback').hidden=true;$('quizbox').hidden=true;['download','copy','print'].forEach(k=>$(k).disabled=true)}};
function showQuestion(){$('question').textContent=`第 ${qi+1}/${quiz.length} 題：${quiz[qi][0]}`;$('answer').value='';$('answer').disabled=false;$('checkanswer').disabled=false;$('nextquestion').disabled=true;$('quizstatus').textContent='先作答，再核對參考答案。'}
const norm=s=>s.normalize('NFKC').trim().toLowerCase().replace(/\s+/g,' ');
$('checkanswer').onclick=()=>{if(!$('answer').value.trim()){$('quizstatus').textContent='請先輸入答案。';return}const ok=norm($('answer').value)===norm(quiz[qi][1]);if(ok)score++;else missed.push(quiz[qi]);$('quizstatus').textContent=(ok?'文字比對相符。':'文字比對不同；請自行確認同義回答。')+' 參考答案：'+quiz[qi][1];$('checkanswer').disabled=true;$('answer').disabled=true;$('nextquestion').disabled=false;$('nextquestion').textContent=qi===quiz.length-1?'完成練習':'下一題'};
$('nextquestion').onclick=()=>{qi++;if(qi<quiz.length)showQuestion();else{$('quizbox').hidden=true;output=`練習完成：${quiz.length} 題；文字比對相符 ${score} 題。\n\n需複習（含可能同義但文字不同）：\n${missed.length?missed.map(([q,a])=>q+' → '+a).join('\n'):'本輪無錯題。'}\n\n核對僅採正規化文字相等，不是語意評分。`;$('result').textContent=output;complete()}};
$('download').onclick=()=>{const b=new Blob(['# '+current.title+'\n\n'+output+'\n\n---\n由行動20在本機產出；請人工確認。\n'],{type:'text/markdown;charset=utf-8'});const u=URL.createObjectURL(b),a=el('a');a.href=u;a.download='action20-'+current.id+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);message('已交由瀏覽器匯出檔案。')};
async function copy(s){try{await navigator.clipboard.writeText(s);message('已複製。')}catch{message('無法自動複製，請選取下列文字自行複製：');const p=el('pre',s);$('notice').append(p)}}
$('copy').onclick=()=>copy(output);$('print').onclick=()=>window.print();$('share').onclick=()=>copy(BASE+'?tool='+current.id+'&utm_source=share');
$('consent').checked=store.get('consent')==='1';$('consent').onchange=()=>{try{store.set('consent',$('consent').checked?'1':'0')}catch{message('瀏覽器未允許儲存偏好。')}if($('consent').checked){metric(['visitors','source-'+source+'-visitors']);message('同意只影響之後的使用；先前的演示不補算。')}else message('已停止之後的計數；已彙總的數字不會被刪除。')};
async function feedback(kind){if(!isReal){message('範例／測試不列入回饋。可到 GitHub 留下操作建議。');return}if(!$('consent').checked){message('匿名選項回饋需先同意下方計數；也可直接使用 GitHub 公開留言。');return}const ok=await metric(['visitors','completers','feedback','feedback-'+current.id,kind+'-'+current.id+'-'+$('reason').value]);message(ok?'選項回饋已送達；同一選項在此瀏覽器只計一次。':'回饋未完整送達，請改用 GitHub 公開留言。')}
$('yes').onclick=()=>feedback('helpful');$('no').onclick=()=>feedback('unhelpful');$('realaction').onclick=async()=>{if(!isReal||!$('consent').checked){message('只有真實資料且同意計數後才能送出；請勿把演示當實際行動。');return}const ok=await metric(['visitors','completers','real','real-'+current.id]);message(ok?'已記錄你的自述，不代表第三方已查證。':'自述未完整送達。')};
$('refresh').onclick=async()=>{if(test){$('metricstatus').textContent='測試模式：不連線、不讀寫正式計數。';return}$('metricstatus').textContent='讀取中…';const keys=['visitors','completers','feedback','real'];await Promise.all(keys.map(async k=>{try{const v=await request('get',k);document.querySelector(`[data-m=${k}]`).textContent=v}catch{document.querySelector(`[data-m=${k}]`).textContent='不可用'}}));$('metricstatus').textContent='僅供初步驗證；不可用不是 0。去重依此瀏覽器的本機標記，並未驗證真人。'};
$('forget').onclick=()=>{try{Object.keys(localStorage).filter(k=>k.startsWith('a20:')).forEach(k=>localStorage.removeItem(k));$('consent').checked=false;$('metricstatus').textContent='已清除本機偏好與標記並停止計數；公開彙總未刪除。'}catch{$('metricstatus').textContent='瀏覽器不允許存取本機儲存。'}};
if(params.has('tool'))openTool(params.get('tool'));if(test)$('metricstatus').textContent='測試模式：範例與自動化測試不連線、不污染採用數。';else if($('consent').checked)metric(['visitors','source-'+source+'-visitors']);
