/* Action20 v1.0 · MIT · Deterministic, local-only tools. */
(function(root){
'use strict';
const F=(id,label,type,example)=>({id,label,type,example});
const T=(id,title,group,audience,desc,fields,next,run)=>({id,title,group,audience,desc,fields,next,run});
const text=(v)=>String(v??'').trim();
const n=(v,min=0,max=1e9)=>{if(text(v)===''||!Number.isFinite(Number(v))||Number(v)<min||Number(v)>max)throw Error(`數值須介於 ${min} 與 ${max}。`);return Number(v)};
const integer=(v,min=0,max=10000)=>{const x=n(v,min,max);if(!Number.isInteger(x))throw Error('請填整數。');return x};
const lines=(v)=>{const a=text(v).split(/\r?\n/).filter(x=>x.trim());if(!a.length||a.length>100)throw Error('請填 1–100 行資料。');return a};
const rows=(v,k)=>lines(v).map((s,i)=>{const a=s.split(/[|｜]/).map(text);if(a.length!==k||a.some(x=>!x))throw Error(`第 ${i+1} 行需要 ${k} 欄，請用 | 分隔；每欄不可空白。`);return a});
const date=(s)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Error('日期請用 YYYY-MM-DD。');const d=new Date(s+'T00:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==s)throw Error('日期不存在。');return d};
const fmt=(v)=>Number(v.toFixed(2)).toLocaleString('zh-TW');
const table=(head,rs)=>[head.join(' | '),head.map(()=> '---').join(' | '),...rs.map(r=>r.join(' | '))].join('\n');
const sum=(a)=>a.reduce((x,y)=>x+y,0);
const tools=[
T('priority','需求優先排序','找對問題','服務性社團企劃、社區召集人','把想做的事情排出先後，不把主觀分數當事實。',[F('items','每行：需求 | 影響 1–5 | 急迫 1–5 | 工時','textarea','物資盤點 | 4 | 5 | 2\n招募新志工 | 5 | 3 | 6\n製作海報 | 2 | 2 | 3')],'先找一位實際使用者確認排名第一的需求。',v=>{const r=rows(v.items,4).map(([a,b,c,d])=>[a,n(b,1,5),n(c,1,5),n(d,.1,10000)]).map(r=>[...r,r[1]*r[2]/r[3]]).sort((a,b)=>b[4]-a[4]);return '自訂啟發式：影響 × 急迫 ÷ 工時；不是客觀效益估計。\n\n'+table(['需求','影響','急迫','工時','排序分數'],r.map(a=>a.map(x=>typeof x==='number'?fmt(x):x)))}),
T('brief','一頁行動提案','找對問題','公益專案提案人','將對象、證據與最小測試整理成一頁。',[F('who','服務對象','text','第一次帶隊的服務性社團幹部'),F('problem','遇到的具體困難','textarea','每次活動前都重做排班表。'),F('evidence','已觀察到的證據；沒有就填尚待訪談','textarea','尚待訪談，不假設已被驗證。'),F('test','最小測試與完成條件','textarea','邀請 3 位幹部用一次排班工具，確認是否實際採用。')],'把提案交給目標使用者，詢問問題描述是否符合經驗。',v=>`服務對象：${v.who}\n\n待解決問題：${v.problem}\n\n目前證據：${v.evidence}\n\n最小測試：${v.test}\n\n決策門檻：先填入測試期限、負責人及停止條件，再投入更多資源。`),
T('interview','需求訪談小抄','找對問題','學生志工、公益產品研究者','產生以最近一次經驗為主的訪談問題，不代填答案。',[F('who','受訪角色（不要填真名）','text','社區志工召集人'),F('topic','想了解的任務','text','活動前安排志工'),F('assumption','你想驗證的假設','text','大家最困擾的是臨時缺席')],'取得同意後訪談一人；不要把假設說成對方的答案。',v=>`對象：${v.who}\n任務：${v.topic}\n待驗證而非既定事實：${v.assumption}\n\n開場：這次只了解經驗，可跳題或隨時停止；未獲同意不錄音。\n\n1. 請回想最近一次「${v.topic}」，當時怎麼開始？\n2. 中間哪一步最費力？可以描述當時發生的事嗎？\n3. 你實際用了哪些方法處理？\n4. 花了多少時間？不清楚也沒關係。\n5. 有沒有一次反而很順利？差別在哪？\n6. 還有什麼比這個問題更值得先處理？\n\n紀錄分三欄：原話／觀察／我的推測。不要記不必要的個資。`),
T('roster','志工排班與缺口','把活動辦好','5–20 人服務隊的排班幹部','依可出席時段與每人上限產生初稿，明列未補滿名額。',[F('people','每行：志工代號 | 可出席時段（逗號分隔）','textarea','A | 上午,下午\nB | 上午\nC | 下午'),F('slots','每行：時段 | 所需人數（各時段須互不重疊）','textarea','上午 | 2\n下午 | 2'),F('cap','每人最多幾班','number','2')],'請每位志工確認；這是貪婪排班初稿，不保證全域最佳解。',v=>{const p=rows(v.people,2).map(([name,a])=>({name,a:a.split(/[,，]/).map(text),load:0}));if(new Set(p.map(x=>x.name)).size!==p.length)throw Error('志工代號不可重複。');const s=rows(v.slots,2);if(new Set(s.map(x=>x[0])).size!==s.length)throw Error('時段名稱不可重複。');const cap=integer(v.cap,1,20);const rr=s.map(([slot,c])=>{const need=integer(c,1,100);const eligible=p.filter(x=>x.a.includes(slot)&&x.load<cap).sort((a,b)=>a.a.length-b.a.length||a.load-b.load);const picked=eligible.slice(0,need);picked.forEach(x=>x.load++);return [slot,need,picked.map(x=>x.name).join('、')||'無',Math.max(0,need-picked.length)]});return table(['時段','需求','分派代號','缺口'],rr)+'\n\n'+p.map(x=>`${x.name}：${x.load} 班`).join('\n') }),
T('agenda','活動流程時間表','把活動辦好','活動總召、工作坊主持人','依起始時間和每段分鐘數自動排出完整流程。',[F('start','起始時間 HH:MM','time','09:00'),F('items','每行：流程 | 分鐘','textarea','報到 | 20\n破冰 | 15\n服務行動 | 60\n休息 | 10\n回饋 | 15')],'把時間表交給主持與場控，確認轉場時間是否足夠。',v=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(v.start))throw Error('時間格式不正確。');let m=Number(v.start.slice(0,2))*60+Number(v.start.slice(3));const clock=x=>(x>=1440?`+${Math.floor(x/1440)}日 `:'')+String(Math.floor(x%1440/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0');let total=0;const r=rows(v.items,2).map(([a,b])=>{const t=integer(b,1,1440),s=clock(m);m+=t;total+=t;return [s,clock(m),a,t]});return table(['開始','結束','流程','分鐘'],r)+`\n\n總長 ${total} 分鐘。跨日以 +1日 等標記。`}),
T('budget','活動預算與缺口','把活動辦好','學生社團總務、小型 NPO 專案助理','逐項加總成本，計算每人支出及預算缺口。',[F('items','每行：項目 | 數量 | 單價（同一貨幣）','textarea','餐盒 | 30 | 90\n交通 | 1 | 1200\n印刷 | 50 | 2'),F('fund','可用預算','number','4500'),F('people','參與人數','number','30')],'確認報價、稅費與憑證；不要把估計當成已付款。',v=>{const r=rows(v.items,3).map(([a,b,c])=>[a,n(b),n(c),n(b)*n(c)]);const total=sum(r.map(x=>x[3])),fund=n(v.fund),p=integer(v.people,1);return table(['項目','數量','單價','小計'],r.map(a=>a.map(x=>typeof x==='number'?fmt(x):x)))+`\n\n總額：${fmt(total)}\n每人：${fmt(total/p)}\n可用預算：${fmt(fund)}\n${total>fund?'尚缺':'剩餘'}：${fmt(Math.abs(total-fund))}`}),
T('access','友善活動待辦檢查','讓更多人參與','活動場務、志工召集人','依自行勾選的準備事項列出仍待處理的障礙。',[F('done','已確認項目：填編號、逗號分隔；無則填 0。1無階差動線 2可用廁所 3字幕或文字替代 4清楚指引 5可休息座位 6需求聯絡窗口','text','1,4,6')],'與有相關需求的參與者確認；此清單不是無障礙認證。',v=>{const all=['無階差且已實勘的進出動線','可使用的廁所與交通資訊','字幕、文字或其他溝通替代','清楚的大字體與路線指引','可休息的座位與彈性離席','事前需求詢問與聯絡窗口'];const a=v.done.split(/[,，]/).map(text);if(a.some(x=>!/^\d$/.test(x)||+x>6))throw Error('請填 0–6 的編號。');const done=new Set(a.map(Number));return all.map((s,i)=>`${done.has(i+1)?'[x]':'[ ]'} ${i+1}. ${s}`).join('\n')+`\n\n已確認 ${all.filter((_,i)=>done.has(i+1)).length}/6 項；勾選代表自述，並非現場稽核。`}),
T('readable','公告斷句與閱讀檢查','讓更多人參與','社群小編、服務隊文書','依標點分段，標出長句；不宣稱完成語意改寫或易讀認證。',[F('copy','原始公告（不要放個資）','textarea','本週六舉辦物資整理活動，請於上午九點到集合地點報到，並自備水杯。無法參加者請提前告知。')],'請一位目標讀者用自己的話複述公告；再改掉不清楚處。',v=>{const a=v.copy.split(/[。！？；\n]+/).map(text).filter(Boolean);if(!a.length)throw Error('請輸入包含文字的公告。');return a.map((s,i)=>`${i+1}. ${s}。${s.length>40?' ← 超過 40 字，建議再拆句（自訂提醒門檻）':''}`).join('\n\n')+'\n\n人工確認：誰要做什麼？何時？在哪裡？怎麼報名？需要帶什麼？無法參加找誰？\n本工具只做規則式斷句，不判斷內容正確性。'}),
T('contrast','文字色彩對比檢查','讓更多人參與','公益海報設計者、網站志工','計算兩個不透明 sRGB 色碼的對比值與文字門檻。',[F('fg','文字色 #RRGGBB','text','#164B3B'),F('bg','背景色 #RRGGBB','text','#FFFFFF')],'把結果用在文字與背景搭配；仍須檢查字體、操作及其他無障礙要求。',v=>{const l=s=>{if(!/^#[\da-f]{6}$/i.test(s))throw Error('請用六碼色碼，例如 #164B3B。');const a=[1,3,5].map(i=>parseInt(s.slice(i,i+2),16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]};const a=l(v.fg),b=l(v.bg),r=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);return `對比值：${r.toFixed(4)} : 1\n\n一般文字 AA（至少 4.5）：${r>=4.5?'達門檻':'未達門檻'}\n大字 AA（至少 3）：${r>=3?'達門檻':'未達門檻'}\n一般文字 AAA（至少 7）：${r>=7?'達門檻':'未達門檻'}\n\n以未四捨五入數值判定；只檢查對比，不代表整站符合 WCAG。大字定義請見來源。\n來源：https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html`}),
T('handoff','會議待辦與交接','把活動辦好','社團交接幹部、NPO 專案助理','將任務按到期日排序，分開逾期、待辦與完成。',[F('today','檢查基準日','date','2026-09-14'),F('items','每行：任務 | 負責代號 | 到期日 YYYY-MM-DD | 待辦或完成','textarea','確認物資 | A | 2026-09-16 | 待辦\n借場地 | B | 2026-09-12 | 待辦\n寄邀請 | C | 2026-09-10 | 完成')],'由各負責人確認承接；本工具不會自動發送提醒。',v=>{const now=date(v.today);const r=rows(v.items,4).map(a=>{date(a[2]);if(!['待辦','完成'].includes(a[3]))throw Error('狀態請填待辦或完成。');return [...a,a[3]==='完成'?'已完成':date(a[2])<now?'逾期':'待辦']}).sort((a,b)=>a[2].localeCompare(b[2]));return table(['任務','負責','到期','原狀態','檢查'],r)}),
T('meals','活動餐點份數','惜物與永續','活動訂餐幹部、社區共餐協調者','依已確認人數、工作人員與備用比例估計份數。',[F('guests','已確認參加人數','number','30'),F('staff','另需餐點的工作人員','number','5'),F('buffer','自訂備用比例 %（非官方標準）','number','10'),F('vegetarian','上述所有人中，已確認素食份數','number','7')],'再確認特殊飲食、過敏與實際出席；備用餐別先與供餐者協調。',v=>{const base=integer(v.guests)+integer(v.staff),veg=integer(v.vegetarian),extra=Math.ceil(base*n(v.buffer,0,50)/100);if(veg>base)throw Error('素食份數不能超過已確認總人數。');return `已確認：${base} 份\n其中一般餐：${base-veg} 份\n其中素食餐：${veg} 份\n另外備用：${extra} 份（餐別待確認）\n\n預估總量：${base+extra} 份\n工作人員不可重複算入參加人數。此為份數估算，不是營養或食品安全判斷。`}),
T('supplies','物資需求缺口表','惜物與永續','募物資志工、公益倉管','逐項比較需求與已確認可用數量，避免重複募集。',[F('items','每行：物資 | 單位 | 所需 | 已確認可用','textarea','筆記本 | 本 | 50 | 32\n鉛筆 | 支 | 80 | 100\n紙箱 | 個 | 10 | 3')],'公開缺口前先與受贈單位確認品項、規格及收受意願。',v=>{const r=rows(v.items,4).map(([a,u,b,c])=>{const need=n(b),have=n(c);return [a,u,need,have,Math.max(0,need-have),Math.max(0,have-need)]});return table(['物資','單位','需求','可用','尚缺','多餘'],r)+'\n\n這是你輸入的盤點，不是真實媒合平台；沒有自動通知捐贈者。'}),
T('pantry','期限盤點與先後順序','惜物與永續','宿舍共享櫃管理者、家庭採購者','依你抄錄的日期排序，顯示剩餘天數供人工檢查。',[F('today','盤點日期','date','2026-09-14'),F('items','每行：品項 | 標示日期 YYYY-MM-DD | 數量','textarea','乾麵 | 2026-10-01 | 2\n餅乾 | 2026-09-16 | 3\n備品 | 2026-09-10 | 1')],'先查看標示與保存條件；日期接近或未到，不等於可以安全食用。',v=>{const now=date(v.today);const r=rows(v.items,3).map(([a,d,c])=>[a,d,n(c),Math.round((date(d)-now)/86400000)]).sort((a,b)=>a[3]-b[3]);return table(['品項','你填的日期','數量','距日期天數'],r)+'\n\n負數代表已過你填的日期；不判斷是否可食用，也不提供保存期限建議。'}),
T('reuse','二手物品轉贈文','惜物與永續','學生搬宿舍者、社區交換活動幹部','整理品況、交接方式與保留期限；發布前由你檢查。',[F('item','物品、數量與品況','textarea','檯燈 1 個；可正常使用，底座有刮痕。'),F('area','大致交接區域（不要填住址）','text','臺大公館校區附近公共場所'),F('when','可交接時段','text','週三下午，需事先確認'),F('rule','保留／候補規則','text','依私訊順序確認，24 小時未回覆則詢問下一位。')],'在允許轉贈的社團發文；自行確認安全、真實品況與交接約定。',v=>`【免費轉贈】${v.item}\n\n交接區域：${v.area}\n時段：${v.when}\n規則：${v.rule}\n\n有需要者請私訊確認，勿在公開留言留電話或完整住址。尚未完成預約或交接；本工具不代替你刊登。`),
T('energy','用電情境估算','惜物與永續','宿舍節能幹部、公益辦公室總務','用功率與時間估算用電差，不混入不明排碳係數。',[F('watts','運作功率 W','number','60'),F('count','設備台數','number','5'),F('before','原每日使用小時','number','8'),F('after','新每日使用小時','number','5'),F('days','比較天數','number','30')],'實測設備運轉情況後再更新；不要把額定功率估計當成電表讀數。',v=>{const factor=n(v.watts,0,1e7)*integer(v.count,1)*integer(v.days,1,3660)/1000,b=factor*n(v.before,0,24),a=factor*n(v.after,0,24);return `原情境：${fmt(b)} kWh\n新情境：${fmt(a)} kWh\n差額（原 − 新）：${fmt(b-a)} kWh\n\n公式：W × 台數 × 每日小時 × 天數 ÷ 1000。\n假設輸入功率在使用時段內固定；不含待機、運轉週期、電費或排碳推估。`}),
T('reusables','重複用品成本比較','惜物與永續','活動採購幹部、環保服務隊','比較單次用品與重複用品的自訂金額，不宣稱環境回本。',[F('single','每次一次性用品成本','number','5'),F('buy','一個重複用品購入成本','number','100'),F('wash','每次使用後清洗等成本','number','1'),F('uses','預計使用次數','number','30')],'確認衛生處理、遺失率與實際重用次數；這裡只有成本，不是生命週期評估。',v=>{const s=n(v.single),b=n(v.buy),w=n(v.wash),u=integer(v.uses,1,1e6),delta=s-w;return `一次性累計：${fmt(s*u)}\n重複用品累計：${fmt(b+w*u)}\n成本差（一次性 − 重複）：${fmt(s*u-b-w*u)}\n\n${delta>0?`成本相等或更低的最小整數次數：${Math.max(0,Math.ceil(b/delta))}`:b===0&&delta===0?'兩方案各次成本相同。':'依此假設沒有有限的成本回本次數。'}\n未計破損、物流、用水與環境影響。`}),
T('study','陪讀時間分配','學習與驗證','課輔志工、讀書小組帶領人','按主題優先權分配固定學習時段，保留零分配提醒。',[F('minutes','可用總分鐘','number','120'),F('block','每一時段分鐘','number','20'),F('items','每行：主題 | 自訂優先權 1–5','textarea','分數運算 | 5\n閱讀摘要 | 3\n自然複習 | 2')],'依學生實際作答調整優先權；此分配不保證學習效果。',v=>{const total=integer(v.minutes,1,100000),block=integer(v.block,1,240),b=Math.floor(total/block);if(!b)throw Error('總分鐘至少要容納一個時段。');const r=rows(v.items,2).map(([a,w])=>({a,w:n(w,1,5)})),ws=sum(r.map(x=>x.w));r.forEach(x=>{x.raw=b*x.w/ws;x.blocks=Math.floor(x.raw)});let left=b-sum(r.map(x=>x.blocks));[...r].sort((a,b)=>(b.raw-b.blocks)-(a.raw-a.blocks)).slice(0,left).forEach(x=>x.blocks++);return table(['主題','時段數','分鐘'],r.map(x=>[x.a,x.blocks,x.blocks*block]))+`\n\n保留／轉場：${total-b*block} 分鐘。0 時段的主題須另安排。`}),
T('quiz','自製問答練習','學習與驗證','課輔志工、考試讀書會','把自己的題目變成一題一答，核對答案並保留錯題。',[F('cards','每行：問題 | 參考答案（至少 1 題）','textarea','1 kWh 是幾 Wh？ | 1000\n活動結束後該收集什麼？ | 回饋')],'用錯題再練一次；核對採文字正規化比對，意思相同也可能判不同。',v=>{const r=rows(v.cards,2);return `已建立 ${r.length} 張題卡。請在下方作答；未作答不計為完成練習。`}),
T('outreach','受眾邀請與來源連結','學習與驗證','公益專案推廣者、學生社團小編','替一種受眾產生邀請文及帶來源參數的 HTTPS 連結。',[F('audience','本次只邀請哪一種人','text','正在安排服務活動的社團幹部'),F('benefit','工具能完成的具體事情','text','將志工可出席時段整理成排班初稿'),F('ask','只要求一個小動作','text','完成一份排班，再告訴我們哪一步不好用'),F('url','公開 HTTPS 工具網址','url','https://allen3429.github.io/Allentrial20260812.github.io/public-good/action20/?tool=roster'),F('source','來源代碼：英數、連字號或底線','text','campus-volunteers')],'只發到允許的頻道；尊重版規、拒收與審核，不做大量私訊。',v=>{let u;try{u=new URL(v.url)}catch{throw Error('網址無效。')}if(u.protocol!=='https:'||u.username||u.password)throw Error('請使用不含帳密的 HTTPS 網址。');if(!/^[a-z0-9_-]{1,40}$/i.test(v.source))throw Error('來源代碼請用 1–40 個英數、- 或 _。');u.searchParams.set('utm_source',v.source);u.searchParams.set('utm_medium','community');u.searchParams.set('utm_campaign','action20-launch');return `給 ${v.audience}：\n\n我們做了一個免費小工具，可以${v.benefit}。目前徵求真實試用，不宣稱已有成效。\n\n邀請你：${v.ask}。\n${u.href}\n\n本段是待審核文案；產生連結不等於已發布，也不等於有人點擊。`}),
T('impact','小規模驗證判讀','學習與驗證','公益專案負責人、開源維護者','將不同漏斗數字分開，避免把瀏覽次數當完成或影響。',[F('visitors','同一期間近似獨立瀏覽器數','number','20'),F('completers','其中完成核心工具的瀏覽器數','number','8'),F('feedback','其中留下回饋的瀏覽器數','number','4'),F('real','其中自述採取實際行動的瀏覽器數','number','2'),F('goal','預先訂定的完成者目標','number','10')],'查看文字回饋再決定改善；自述行動不能直接當成已證實的社會影響。',v=>{const a=integer(v.visitors),b=integer(v.completers),c=integer(v.feedback),d=integer(v.real),g=integer(v.goal,1);if(b>a||c>b||d>b)throw Error('此漏斗定義要求：完成者 ≤ 訪客；回饋者與行動者 ≤ 完成者。');return `近似獨立瀏覽器：${a}\n完成者：${b}（${a?fmt(100*b/a)+'%':'無分母，不計轉換率'}）\n回饋者：${c}\n自述實際行動者：${d}\n\n完成者目標 ${g}：${b>=g?'達到預設門檻，仍需確認使用品質':'尚差 '+(g-b)+'，先找出卡住步驟'}\n\n輸入數字由你提供，本工具不驗證真偽。排除內部測試；不同裝置、清除儲存與公開計數器濫用都可能影響數字。`})
];
function execute(id,values){const t=tools.find(x=>x.id===id);if(!t)throw Error('找不到這個工具。');const v={};for(const f of t.fields){v[f.id]=text(values[f.id]);if(!v[f.id])throw Error('請填寫「'+f.label+'」。');if(v[f.id].length>16000)throw Error('單一欄位請勿超過 16,000 字。')}return t.run(v)+'\n\n下一步：'+t.next}
const api={tools,execute,rows,date};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Action20=api;
})(typeof globalThis!=='undefined'?globalThis:this);
