/* ScamShield Campaign Mode */
(()=>{"use strict";
const D=window.SCAMSHIELD_CAMPAIGN_DATA||{stages:[],recovery:{}},S=D.stages,R=D.recovery,$=s=>document.querySelector(s),K={mode:"scamshield.playMode",best:"scamshield.campaign.bestScore",runs:"scamshield.campaign.runs",rate:"scamshield.speechRate"},E={home:$("#briefingPanel"),game:$("#gamePanel"),result:$("#resultPanel"),start:$("#startBtn"),next:$("#replayBtn"),rl:$("#roundLabel"),rt:$("#roundTitle"),speaker:$("#speakerLabel"),bar:$("#shieldBar"),shield:$("#shieldValue"),score:$("#scoreValue"),flags:$("#redFlags"),text:$("#dialogueText"),choices:$("#choiceArea"),lesson:$("#lessonBox"),stop:$("#interruptBtn"),stopMsg:$("#interruptFeedback"),final:$("#finalScore"),resultTitle:$("#resultTitle"),resultCopy:$("#resultCopy"),resultFlags:$("#resultFlags"),why:$("#showWhyBtn"),whyBox:$("#whyBox"),stage:$("#avatarStage"),mount:$("#agentMount"),presenter:$("sv-presenter"),badge:$("#connectionBadge")};
const allowed=new Set(S.flatMap(s=>s.rounds.map(r=>r.speech))),G={active:false,mode:localStorage.getItem(K.mode)||"campaign",si:0,ri:0,score:0,shield:100,flags:[],safe:0,risky:0,streak:0,maxStreak:0,interrupts:0,stageSafe:0,stageRisky:0,stageInterrupts:0,stageResults:[],recoveries:0,presenting:false,interrupted:false,token:0,timer:null,recovery:null,locked:false};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),stage=()=>S[G.si],round=()=>stage()?.rounds[G.ri],globalN=()=>G.si*4+G.ri+1,rate=()=>Number(localStorage.getItem(K.rate))||1.25,ready=()=>E.badge?.classList.contains("badge-online")||/ready/i.test(E.badge?.textContent||"");
function renderer(){const a=E.mount?.querySelector("sv-agent"),p=E.presenter&&!E.presenter.classList.contains("hidden");if(p&&typeof E.presenter.present==="function")return{m:"connect",t:E.presenter};if(a&&typeof a.agentReply==="function")return{m:"widget",t:a};if(typeof E.presenter?.present==="function")return{m:"connect",t:E.presenter};return null}
function modeUI(){if(!E.home||$("#campaignModePicker"))return;const x=document.createElement("section");x.id="campaignModePicker";x.className="campaign-mode-picker";x.innerHTML=`<div class="campaign-mode-head"><div><span>PLAY MODE</span><strong>選擇演練長度</strong></div><small>BEST ${Number(localStorage.getItem(K.best))||0}</small></div><div class="campaign-mode-grid"><button type="button" data-mode="campaign"><b>闖關模式</b><span>3 階段 · 12 回合</span><em>推薦 Demo</em></button><button type="button" data-mode="quick"><b>快速演練</b><span>原版 4 回合</span><em>約 2 分鐘</em></button></div>`;E.start.before(x);x.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{G.mode=b.dataset.mode;localStorage.setItem(K.mode,G.mode);syncMode()});syncMode()}
function syncMode(){$("#campaignModePicker")?.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("is-selected",b.dataset.mode===G.mode));$("#campaignHud")?.classList.toggle("hidden",G.mode!=="campaign"||!G.active);if(!ready())return;const h=G.mode==="campaign"?`開始闖關 <span>12 ROUNDS →</span>`:`快速演練 <span>4 ROUNDS →</span>`;if(E.start.innerHTML!==h)E.start.innerHTML=h;E.start.classList.toggle("campaign-start",G.mode==="campaign")}
function hud(){if($("#campaignHud"))return;const h=document.createElement("div");h.id="campaignHud";h.className="campaign-hud";h.innerHTML=`<div class="campaign-path">${S.map((s,i)=>`<div data-stage="${i}"><i>${i+1}</i><span>${esc(s.name)}</span></div>`).join("")}</div><div class="campaign-stats"><span>COMBO <b id="cCombo">×0</b></span><span>INTERRUPTS <b id="cStops">0</b></span><span>TOTAL <b id="cTotal">1/12</b></span></div>`;E.game.prepend(h)}
function updateHUD(){$("#campaignHud")?.querySelectorAll("[data-stage]").forEach(n=>{const i=+n.dataset.stage;n.classList.toggle("is-active",i===G.si);n.classList.toggle("is-cleared",i<G.si)});$("#cCombo")&&( $("#cCombo").textContent=`×${G.streak}`);$("#cStops")&&($("#cStops").textContent=G.interrupts);$("#cTotal")&&($("#cTotal").textContent=`${globalN()}/12`);E.score.textContent=`${Math.max(0,G.score)} pts`;E.shield.textContent=G.shield;E.bar.style.width=`${G.shield}%`}
function renderFlags(){E.flags.innerHTML=G.flags.length?G.flags.slice(-8).map(f=>`<span class="flag">⚑ ${esc(f)}</span>`).join(""):`<div class="empty-state">你抓到的紅旗會出現在這裡。</div>`}
function flag(f){if(f&&!G.flags.includes(f)){G.flags.push(f);renderFlags()}}
function splash(s,cb){let x=$("#campaignStageSplash");if(!x){x=document.createElement("div");x.id="campaignStageSplash";x.className="campaign-stage-splash";E.stage.append(x)}x.style.setProperty("--stage-color",s.color);x.innerHTML=`<div class="campaign-stage-number">STAGE ${s.number}</div><h2>${esc(s.name)}</h2><p>${esc(s.subtitle)}</p><div>${s.rounds.map((_,i)=>`<span>${i+1}</span>`).join("")}</div>`;x.classList.add("is-visible");setTimeout(()=>{x.classList.remove("is-visible");setTimeout(cb,260)},1200)}
function prop(r){if(!r?.prop)return;let p=$("#ux2HandProp");if(!p){p=document.createElement("div");p.id="ux2HandProp";p.setAttribute("aria-hidden","true");E.stage.append(p)}const q=r.prop;p.className=`ux2-hand-prop campaign-prop campaign-prop-${q.type}`;p.innerHTML=`<div class="ux2-prop-grip"><i></i><i></i><i></i></div><div class="ux2-prop-screen"><div class="ux2-prop-top"><span>${esc(q.eyebrow)}</span><b>${esc(q.code)}</b></div><div class="ux2-prop-icon">${esc(q.icon)}</div><strong>${esc(q.title)}</strong><small>${esc(q.detail)}</small></div>`}
const speechMs=t=>clamp(String(t).length/(3.5*rate())*1000+1700,4300,15000);function widgetEnd(t){try{t?.agentReply?.({event:"agent_end",message:""})}catch{}}
async function speak(r){if(!allowed.has(r.speech))throw Error("Campaign safety boundary");const v=renderer(),token=++G.token;G.presenting=true;G.interrupted=false;clearTimeout(G.timer);E.text.textContent=r.speech;E.stop.disabled=false;E.stop.classList.add("hot");E.stopMsg.textContent="在對方控制你之前，直接中斷並切換驗證通道。";if(!v){finishSpeech(r,token);return}if(v.m==="widget"){v.t.agentReply({event:"agent_answer",message:r.speech,motion_id:"talking"});G.timer=setTimeout(()=>{if(token!==G.token||G.interrupted)return;widgetEnd(v.t);finishSpeech(r,token)},speechMs(r.speech));return}try{await v.t.resumeAudioPlayback?.();await v.t.present(r.speech)}catch(e){if(!G.interrupted)console.warn(e)}finishSpeech(r,token)}
function finishSpeech(r,t){if(t!==G.token||G.interrupted)return;G.presenting=false;E.stop.disabled=true;E.stop.classList.remove("hot");choices(r)}
function renderRound(){const s=stage(),r=round();if(!r)return;G.recovery=null;G.locked=false;document.body.classList.toggle("campaign-boss",G.si===2);E.rl.textContent=`STAGE ${s.number} · ROUND ${G.ri+1}/4 · TOTAL ${globalN()}/12`;E.rt.textContent=r.title;E.speaker.textContent=r.speaker;E.choices.innerHTML="";E.lesson.className="lesson hidden";updateHUD();requestAnimationFrame(()=>prop(r));speak(r)}
function choices(r){if(!G.active||G.locked)return;E.choices.innerHTML=r.choices.map((c,i)=>`<button class="choice campaign-choice" type="button" data-c="${i}"><b>${String.fromCharCode(65+i)}</b><span>${esc(c.text)}</span></button>`).join("");E.choices.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>choose(+b.dataset.c))}
function apply(c,recovery=false){G.score+=c.points||0;G.shield=clamp(G.shield+(c.shield||0),0,100);if(recovery){if(c.ok)G.recoveries++}else if(c.ok){G.safe++;G.stageSafe++;G.streak++;G.maxStreak=Math.max(G.maxStreak,G.streak);if(G.streak>=2)G.score+=3}else{G.risky++;G.stageRisky++;G.streak=0}if(c.addFlag)flag(c.addFlag);updateHUD()}
function choose(i){if(G.locked)return;G.locked=true;const r=round(),c=r.choices[i];E.choices.innerHTML="";apply(c);E.lesson.className=`lesson ${c.ok?"":"bad"}`;E.lesson.textContent=`${c.ok?"✓":"⚠"} ${c.lesson}`;E.lesson.classList.remove("hidden");if(!c.ok&&c.recovery&&R[c.recovery])setTimeout(()=>recovery(R[c.recovery]),1050);else setTimeout(advance,1300)}
function recovery(x){G.recovery=x;G.locked=false;E.rt.textContent=x.title;E.speaker.textContent="SYSTEM · INCIDENT RECOVERY";E.text.textContent=x.prompt;E.lesson.className="lesson hidden";E.choices.innerHTML=x.choices.map((c,i)=>`<button class="choice campaign-choice recovery-choice" type="button" data-r="${i}"><b>${String.fromCharCode(65+i)}</b><span>${esc(c.text)}</span></button>`).join("");E.choices.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>chooseRecovery(+b.dataset.r))}
function chooseRecovery(i){if(G.locked||!G.recovery)return;G.locked=true;const c=G.recovery.choices[i];E.choices.innerHTML="";apply(c,true);E.lesson.className=`lesson ${c.ok?"":"bad"}`;E.lesson.textContent=`${c.ok?"✓ RECOVERED":"⚠ DAMAGE CONTINUES"} · ${c.lesson}`;E.lesson.classList.remove("hidden");setTimeout(advance,1200)}
function advance(){G.locked=false;G.recovery=null;G.ri++;G.ri>=stage().rounds.length?checkpoint():renderRound()}
const stars=()=>G.stageSafe>=3?3:G.stageSafe>=2?2:1;function checkpoint(){clearTimeout(G.timer);const s=stage(),st=stars();G.stageResults.push({stage:s.number,stars:st,safe:G.stageSafe,risky:G.stageRisky,interrupts:G.stageInterrupts,shield:G.shield});E.game.classList.add("hidden");E.result.classList.remove("hidden");E.whyBox.classList.add("hidden");if(G.si===S.length-1){final();return}const heal=Math.min(12,100-G.shield);G.shield+=heal;E.final.textContent="★".repeat(st);E.resultTitle.textContent=`STAGE ${s.number} CLEARED · ${s.name}`;E.resultCopy.textContent=`安全決策 ${G.stageSafe}/4，風險決策 ${G.stageRisky}，主動中斷 ${G.stageInterrupts} 次。Checkpoint 修復 Trust Shield +${heal}。`;E.resultFlags.innerHTML=G.flags.slice(-6).map(f=>`<span class="flag">✓ ${esc(f)}</span>`).join("");E.next.textContent=`進入 STAGE ${s.number+1}`;E.next.dataset.campaign="next";E.why.textContent="為什麼一定要 Avatar？";map()}
function map(){let m=$("#campaignCheckpointMap");if(!m){m=document.createElement("div");m.id="campaignCheckpointMap";m.className="campaign-checkpoint-map";E.resultFlags.after(m)}m.innerHTML=S.map((s,i)=>{const z=G.stageResults[i],c=z?"is-cleared":i===G.si+1?"is-next":"is-locked";return`<div class="${c}"><i>${s.number}</i><span><b>${esc(s.name)}</b><small>${z?"★".repeat(z.stars):i===G.si+1?"NEXT":"LOCKED"}</small></span></div>`}).join("")}
function score(){const d=G.safe/12*68,h=G.shield/100*20,i=Math.min(1,G.interrupts/6)*8,r=G.risky?Math.min(4,G.recoveries/Math.max(1,G.risky)*4):4;return clamp(Math.round(d+h+i+r),0,100)}
function final(){const n=score(),best=Number(localStorage.getItem(K.best))||0;localStorage.setItem(K.best,Math.max(best,n));localStorage.setItem(K.runs,(Number(localStorage.getItem(K.runs))||0)+1);E.final.textContent=n;E.resultTitle.textContent=n>=88?"CAMPAIGN CLEARED · 你守住了整條信任鏈。":n>=68?"CAMPAIGN CLEARED · 你會防守，但仍有可被施壓的缺口。":"CAMPAIGN COMPLETE · 下一輪要更早中斷。";E.resultCopy.textContent=`12 回合完成：安全決策 ${G.safe}，風險決策 ${G.risky}，主動中斷 ${G.interrupts}，最高連擊 ×${G.maxStreak}，Trust Shield ${G.shield}。`;E.resultFlags.innerHTML=G.stageResults.map(z=>`<span class="flag">STAGE ${z.stage} ${"★".repeat(z.stars)}</span>`).join("");E.next.textContent="再闖一次";E.next.dataset.campaign="restart";E.why.textContent="為什麼一定要 Avatar？";$("#campaignCheckpointMap")?.remove()}
function nextStage(){G.si++;G.ri=0;G.stageSafe=G.stageRisky=G.stageInterrupts=0;E.result.classList.add("hidden");E.game.classList.remove("hidden");updateHUD();splash(stage(),renderRound)}
function reset(){Object.assign(G,{active:true,si:0,ri:0,score:0,shield:100,flags:[],safe:0,risky:0,streak:0,maxStreak:0,interrupts:0,stageSafe:0,stageRisky:0,stageInterrupts:0,stageResults:[],recoveries:0,presenting:false,interrupted:false,recovery:null,locked:false});G.token++;clearTimeout(G.timer)}
function start(){if(!ready()){$("#settingsDialog")?.showModal?.();return}reset();hud();$("#campaignHud")?.classList.remove("hidden");E.home.classList.add("hidden");E.result.classList.add("hidden");E.game.classList.remove("hidden");E.next.dataset.campaign="";renderFlags();updateHUD();splash(stage(),renderRound)}
function interrupt(){if(!G.active||!G.presenting||G.interrupted)return;G.interrupted=true;G.presenting=false;G.token++;clearTimeout(G.timer);const v=renderer();try{v?.m==="widget"?widgetEnd(v.t):v?.t?.interruptPresentation?.()}catch{}G.score+=5;G.interrupts++;G.stageInterrupts++;flag(round()?.flag);E.stop.disabled=true;E.stop.classList.remove("hot");E.stopMsg.textContent="+5 · 你切斷了對方控制的談話節奏。";updateHUD();setTimeout(()=>choices(round()),380)}
function capture(e){const a=e.target.closest?.("#startBtn");if(a&&G.mode==="campaign"){e.preventDefault();e.stopImmediatePropagation();start();return}const b=e.target.closest?.("#interruptBtn");if(b&&G.active){e.preventDefault();e.stopImmediatePropagation();interrupt();return}const c=e.target.closest?.("#replayBtn");if(c&&G.active){e.preventDefault();e.stopImmediatePropagation();c.dataset.campaign==="next"?nextStage():start()}}
function boot(){modeUI();hud();new MutationObserver(syncMode).observe(E.badge,{attributes:true,childList:true,subtree:true});new MutationObserver(syncMode).observe(E.start,{attributes:true,childList:true,subtree:true});document.addEventListener("click",capture,true);syncMode();document.documentElement.classList.add("campaign-mode-ready")}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot,{once:true}):boot();
})();